<div>
    <table border="1">
        <tr>
            <th>Id</th>
            <th>Url</th>
            <th>Title</th>
            <th>Description</th>
            <th>CreationAt</th>
            <th>ModifiedAt</th>
        </tr>
        <?php foreach($this->bookmarks as $bookmark): ?>
        <tr>
            <td><?php echo $this->escapeHtml($bookmark->getId()); ?></td>
            <td><?php echo $this->escapeHtml($bookmark->getUrl()); ?></td>
            <td><?php echo $this->escapeHtml($bookmark->getTitle()); ?></td>
            <td><?php echo $this->escapeHtml($bookmark->getDescription()); ?></td>
            <td><?php echo $this->escapeHtml($bookmark->getCreationAt()); ?></td>
            <td><?php echo $this->escapeHtml($bookmark->getModifiedAt()); ?></td>
            <td><a href="<?php echo $this->url('bookmark\account\view', ['id' => $bookmark->getId()]) ?>">View</a></td>
            <td><a href="<?php echo $this->url('bookmark\account\update', ['id' => $bookmark->getId()]) ?>">Update</a></td>
            <td><a href="<?php echo $this->url('bookmark\account\delete', ['id' => $bookmark->getId()]) ?>">Delete</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>

<div>
    <p><a href="<?php echo $this->url('bookmark\account\create') ?>">Create a new Bookmark</a> </p>
</div>