<div class="lead"><a href="<?php echo $this->url('user\users\view', ['id' => $this->identity()->id]) ?>">@<?php echo $this->identity()->username; ?></a></div>
<div>
    <table border="1">
        <tr>
            <th>Id</th>
            <th>Url</th>
            <th>Title</th>
            <th>Description</th>
            <th>CreationAt</th>
            <th>ModifiedAt</th>
        </tr>
        <?php foreach($this->bookmarks as $bookmark): ?>
        <tr>
            <td><?php echo $this->escapeHtml($bookmark->getId()); ?></td>
            <td><?php echo $this->escapeHtml($bookmark->getUrl()); ?></td>
            <td><?php echo $this->escapeHtml($bookmark->getTitle()); ?></td>
            <td><?php echo $this->escapeHtml($bookmark->getDescription()); ?></td>
            <td><?php echo $this->escapeHtml($bookmark->getCreationAt()); ?></td>
            <td><?php echo $this->escapeHtml($bookmark->getModifiedAt()); ?></td>
            <td><a href="<?php echo $this->url('bookmark\account\view', ['id' => $bookmark->getId()]) ?>">View</a></td>
            <?php if ($this->layout()->acl->isAllowed($this->identity()->role, 'bookmark\account\update')): ?>
                <td><a class="btn btn-success" href="<?php echo $this->url('bookmark\account\update', ['id' => $bookmark->getId()]) ?>">Update</a></td>
            <?php endif; ?>
            <?php if ($this->layout()->acl->isAllowed($this->identity()->role, 'bookmark\account\delete')): ?>
                <td><a class="btn btn-danger" href="<?php echo $this->url('bookmark\account\delete', ['id' => $bookmark->getId()]) ?>">Delete</a></td>
            <?php endif; ?>
        </tr>
        <?php endforeach; ?>
    </table>
</div>

<div>
    <?php if ($this->layout()->acl->isAllowed($this->identity()->role, 'bookmark\account\create')): ?>
        <p><a href="<?php echo $this->url('bookmark\account\create') ?>">Create a new Bookmark</a></p>
    <?php endif; ?>
    <p><a href="<?php echo $this->url('user\users\index') ?>">Users</a> | <a href="<?php echo $this->url('user\login\logout') ?>">Logout</a> </p>
</div>