<div>
    <p><strong>Id:</strong> <?php echo $this->bookmark->getId() ?></p>
    <p><strong>Url:</strong> <?php echo $this->bookmark->getUrl() ?></p>
    <p><strong>Title:</strong> <?php echo $this->bookmark->getTitle() ?></p>
    <p><strong>Description:</strong> <?php echo $this->bookmark->getDescription() ?></p>
    <p><strong>CreationAt:</strong> <?php echo $this->bookmark->getCreationAt() ?></p>
    <p><strong>ModifiedAt:</strong> <?php echo $this->bookmark->getModifiedAt() ?></p>
</div>
