<?php
    $id         = (isset($this->id) ? $this->id : '');
    $url      = (isset($this->url) ? $this->url : '');
    $title   = (isset($this->title) ? $this->title : '');
    $description       = (isset($this->description) ? $this->description : '');
    $creationAt       = (isset($this->creationAt) ? $this->creationAt : '');
    $modifiedAt       = (isset($this->modifiedAt) ? $this->modifiedAt : '');

?>

<div>
    <form id="form1" action="<?php echo $this->action ?>" method="post">
        <!-- Disabled fields will not be sent in $_POST so we have to create hidden fields -->
        <table>
            <tr>
                <td><strong>Url:</strong></td>
                <td><input type="text" name="url" value="<?php echo $url ?>"></td>
            </tr>
            <tr>
                <td><strong>Title:</strong></td>
                <td><input type="text" name="title" value="<?php echo $title ?>"></td>
            </tr>
            <tr>
                <td><strong>Description:</strong></td>
                <td><input type="text" name="description" value="<?php echo $description ?>"></td>
            </tr>
            <tr align="right">
                <td colspan="2"><input type="submit"></td>
            </tr>
        </table>
    </form>
</div>